// Store all the single digit numbers inside a variable to be used in our 6 digit verification code
let numbers = [0, 1, 2, 3, 4, 5, 6, 7, ,8, 9];

// Generate 6 random digits and store them in a variable 
let digit1 = Math.floor(Math.random() * (numbers.length - 1));
let digit2 = Math.floor(Math.random() * (numbers.length - 1));
let digit3 = Math.floor(Math.random() * (numbers.length - 1));
let digit4 = Math.floor(Math.random() * (numbers.length - 1));
let digit5 = Math.floor(Math.random() * (numbers.length - 1));
let digit6 = Math.floor(Math.random() * (numbers.length - 1));

// Concatenate all 6 randomly generated digits into a single 6 digit number
generated_code = `${digit1}${digit2}${digit3}${digit4}${digit5}${digit6}`;

// Display the first random generated 6 digit number once the user opens the 2FA
document.getElementById("authenticator_code").innerText = generated_code;

// Create a function that randomly generates a 6 digit number
function random_code() {

    // Generate 6 random digits and store them in a variable
    let digit01 = Math.floor(Math.random() * (numbers.length - 1));
    let digit02 = Math.floor(Math.random() * (numbers.length - 1));
    let digit03 = Math.floor(Math.random() * (numbers.length - 1));
    let digit04 = Math.floor(Math.random() * (numbers.length - 1));
    let digit05 = Math.floor(Math.random() * (numbers.length - 1));
    let digit06 = Math.floor(Math.random() * (numbers.length - 1));

    // Concatenate all 6 randomly generated digits into a single 6 digit number
    generated_code = `${digit01}${digit02}${digit03}${digit04}${digit05}${digit06}`;

    // Display the randomly generated number
    document.getElementById("authenticator_code").innerText = generated_code;
}

// Display a countdown that displays how much time is left until a new generated 6 digit number is randomly generated 
let timeleft = 9;
let timertest = setInterval(function(){
    if (timeleft == 0) {
        timeleft = 10;
    }
    document.getElementById("countdown").innerText = `${timeleft} seconds until a new code is generated`;
    timeleft -= 1;
}, 1000);

// Create a function that checks to see if the inputted number matches the current one generated by the 2FA
function authenticate() {

    // Get the user's input
    let user_input = document.getElementById("authenticator_form").value;   

    // Compare the user's input with the number generated by the 2FA
    if (user_input == generated_code) {
        alert("You now have access");
        access_redirect();
    } else {
        alert("Access denied");
    }
}

// Redirect the user to the homepage if their input matched their 2FA number
function access_redirect() {
    window.open("homepage.html", target="_blank");
}

// Call the necessary functions 
let new_code = setInterval(random_code, 10000);